// <auto-generated>
#nullable enable

using RhinoDB.Core.Tables;

namespace RhinoDB.Sandbox.MigrationFixture.SchemaHistory.Revision0;

[FrozenSchema(0)]
public readonly partial record struct Player_Rev0([PrimaryKey] int Id, string Name);
