<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MemoryPack" Version="1.21.4"/>
        <PackageReference Include="MessagePack" Version="3.1.9"/>
        <PackageReference Include="System.IO.Hashing" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RhinoDB.Core\RhinoDB.Core.csproj"/>
        <ProjectReference Include="..\RhinoDB.Native\RhinoDB.Native.csproj"/>
        <ProjectReference Include="..\RhinoDB.SchemaContracts\RhinoDB.SchemaContracts.csproj"/>
    </ItemGroup>

</Project>
