using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RhinoDB.Generators;

// [CustomType] gives a standalone (non-[Table]) record struct the same three-pipeline treatment
// TableGenerator gives a row: a hand-rolled, composable Raw writer/reader (used both standalone and
// inlined by a containing row's own Raw serializer via TableGenerator.EmitWriteField/EmitReadField - see
// the RowFieldModel.IsCustomType branch there), plus VersionedMemoryPack/MessagePack thin wrappers.
// Fixes a real gap: without this, a row's Raw serializer falls through to MemoryPack's WriteValue<T>/
// ReadValue<T> generic dispatch for CustomType fields, silently depending on the attribute-driven
// generator succeeding even on the WAL/cold-storage/ring-buffer critical path.
[Generator]
public sealed class CustomTypeGenerator : IIncrementalGenerator {
    static private readonly DiagnosticDescriptor MissingSerializationAttributesDiagnostic = new(
        "RHINO017",
        "CustomType missing mandatory IDC/client serialization attributes",
        "Type '{0}' is [CustomType]-attributed but is missing {1} - every custom type must carry both "
        + "[MemoryPackable] and [MessagePackObject], the same mandatory contract [Table] row types have, "
        + "so IDC and client access always have a real, source-generated formatter available",
        "RhinoDB.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var results = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                TableGenerator.CustomTypeAttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => ToCustomTypeModel(ctx)
            );

        context.RegisterSourceOutput(results, static (spc, result) => {
            foreach (var diagnostic in result.Diagnostics) spc.ReportDiagnostic(diagnostic);
            if (result.Model is not null) spc.AddSource($"{result.Model.SimpleName}.CustomType.g.cs", Emit(result.Model));
        });
    }

    static private (CustomTypeModel? Model, ImmutableArray<Diagnostic> Diagnostics) ToCustomTypeModel(GeneratorAttributeSyntaxContext ctx) {
        var type = (INamedTypeSymbol)ctx.TargetSymbol;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        var missingSerializationAttrs = ImmutableArray.CreateBuilder<string>();
        if (!TableGenerator.HasMemoryPackable(type)) missingSerializationAttrs.Add("[MemoryPackable]");
        if (!TableGenerator.HasMessagePackObject(type)) missingSerializationAttrs.Add("[MessagePackObject]");
        if (missingSerializationAttrs.Count > 0) {
            diagnostics.Add(Diagnostic.Create(
                MissingSerializationAttributesDiagnostic, ctx.TargetNode.GetLocation(), type.Name, string.Join(" and ", missingSerializationAttrs)));
            return (null, diagnostics.ToImmutable());
        }

        var primaryCtor = type.InstanceConstructors.FirstOrDefault(c =>
            c.Parameters.Length > 0 && !(c.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(c.Parameters[0].Type, type))
        );

        if (primaryCtor is not null) {
            diagnostics.AddRange(TableGenerator.CheckOtherKindFieldAttributes(primaryCtor.Parameters, type.Name, ctx.TargetNode.GetLocation()));
            if (diagnostics.Count > 0) return (null, diagnostics.ToImmutable());
        }

        var fields = primaryCtor is null
            ? ImmutableArray<TableGenerator.RowFieldModel>.Empty
            : TableGenerator.ToRowFieldModels(primaryCtor.Parameters);

        var model = new CustomTypeModel(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString(),
            fields
        );
        return (model, diagnostics.ToImmutable());
    }

    static private string Emit(CustomTypeModel model) {
        var sb = new StringBuilder();
        var type = model.FullName;
        var opsName = $"{model.SimpleName}CustomTypeOps";

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using RhinoDB.Core;");
        sb.AppendLine();
        if (model.Namespace is not null) {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"internal static class {opsName} {{");

        // Composable Raw write/read - writes/reads directly into a caller-supplied writer/reader, so a
        // containing row's own Raw serializer (or another CustomType's) can inline this type's fields
        // into the SAME buffer, with no intermediate byte[] allocation and no dependency on MemoryPack's
        // attribute-driven formatter dispatch.
        sb.AppendLine($"    internal static void WriteRaw<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, {type} value) where TBufferWriter : IBufferWriter<byte> {{");
        foreach (var f in model.Fields) TableGenerator.EmitWriteField(sb, f, $"value.{f.FieldName}");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static {type} ReadRaw(ref MemoryPackReader reader) {{");
        foreach (var f in model.Fields) TableGenerator.EmitReadField(sb, f);
        sb.Append($"        return new {type}(");
        sb.Append(string.Join(", ", model.Fields.Select(f => $"{TableGenerator.Camel(f.FieldName)}Value")));
        sb.AppendLine(");");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Standalone byte[] round trip - API parity with a table row's SerializeRow/DeserializeRow, for
        // direct testing or a top-level caller that isn't embedding this type inside a row.
        sb.AppendLine($"    internal static byte[] SerializeRow({type} value) {{");
        sb.AppendLine("        var bufferWriter = new PooledBufferWriter(256);");
        sb.AppendLine("        var writerState = MemoryPackWriterOptionalStatePool.Rent(null);");
        sb.AppendLine("        var writer = new MemoryPackWriter<PooledBufferWriter>(ref bufferWriter, writerState);");
        sb.AppendLine("        WriteRaw(ref writer, value);");
        sb.AppendLine("        writer.Flush();");
        sb.AppendLine("        var result = bufferWriter.WrittenSpan.ToArray();");
        sb.AppendLine("        bufferWriter.Dispose();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static {type} DeserializeRow(byte[] bytes) {{");
        sb.AppendLine("        var readerState = MemoryPackReaderOptionalStatePool.Rent(null);");
        sb.AppendLine("        var reader = new MemoryPackReader(bytes, readerState);");
        sb.AppendLine("        var result = ReadRaw(ref reader);");
        sb.AppendLine("        reader.Dispose();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static byte[] SerializeVersionedMemoryPack({type} value) => MemoryPackSerializer.Serialize(value);");
        sb.AppendLine($"    internal static {type} DeserializeVersionedMemoryPack(byte[] bytes) => MemoryPackSerializer.Deserialize<{type}>(bytes)!;");
        sb.AppendLine($"    internal static byte[] SerializeMessagePack({type} value) => MessagePackSerializer.Serialize(value);");
        sb.AppendLine($"    internal static {type} DeserializeMessagePack(byte[] bytes) => MessagePackSerializer.Deserialize<{type}>(bytes);");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class CustomTypeModel(string fullName, string simpleName, string? @namespace, ImmutableArray<TableGenerator.RowFieldModel> fields) {
        public string FullName { get; } = fullName;
        public string SimpleName { get; } = simpleName;
        public string? Namespace { get; } = @namespace;
        public ImmutableArray<TableGenerator.RowFieldModel> Fields { get; } = fields;
    }
}
