using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RhinoDB.Generators;

[Generator]
public sealed class DbErrorGenerator : IIncrementalGenerator {
    private const string AttributeFullName = "RhinoDB.Core.Exceptions.GenerateDbErrorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ToModel((INamedTypeSymbol)ctx.TargetSymbol))
            .Collect();

        context.RegisterSourceOutput(models, static (spc, errors) => Emit(spc, errors));
    }

    static private ErrorModel ToModel(INamedTypeSymbol exceptionType) {
        const string suffix = "Exception";
        var typeName = exceptionType.Name;
        var factoryName = typeName.EndsWith(suffix)
            ? typeName.Substring(0, typeName.Length - suffix.Length)
            : typeName;

        return new ErrorModel(exceptionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), factoryName);
    }

    static private void Emit(SourceProductionContext context, ImmutableArray<ErrorModel> errors) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by RhinoDB.Generators.DbErrorGenerator from every [GeneratesDbError] exception.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RhinoDB.Core;");
        sb.AppendLine();

        sb.AppendLine("public enum ErrorKind : byte {");
        sb.AppendLine("    SystemFailure,");
        foreach (ErrorModel? error in errors)
            sb.AppendLine($"    {error.FactoryName},");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public readonly partial struct DbError {");
        foreach (ErrorModel? error in errors)
            sb.AppendLine($"    public static DbError {error.FactoryName}() => new(ErrorKind.{error.FactoryName});");
        sb.AppendLine();

        sb.AppendLine("    public Exception ToException() => Kind switch {");
        sb.AppendLine("        ErrorKind.SystemFailure => systemException!,");
        foreach (ErrorModel? error in errors)
            sb.AppendLine($"        ErrorKind.{error.FactoryName} => new {error.ExceptionType}(),");
        sb.AppendLine("        _ => new Exception(\"Unexpected error, empty exception caught\")");
        sb.AppendLine("    };");

        sb.AppendLine("}");

        context.AddSource("DbError.g.cs", sb.ToString());
    }

    private sealed class ErrorModel(string exceptionType, string factoryName) {
        public string ExceptionType { get; } = exceptionType;
        public string FactoryName { get; } = factoryName;
    }
}
