using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using RhinoDB.SchemaContracts;

namespace RhinoDB.Generators;

// A [FrozenSchema(Revision=N)] type is a captured old shape of a former [Table] row - it exists purely so
// the migration engine (Phase 4) and genesis replay (Phase 5) can decode archived Raw bytes written under
// an older revision. Unlike [Table]/[CustomType], it never carries [MemoryPackable]/[MessagePackObject] -
// nothing ever sends a frozen row over IDC/Client, so that mandatory-attribute contract (RHINO015/RHINO017)
// deliberately does not apply here. It does still need [PrimaryKey] on one field, mirroring a live row,
// since archived WAL entries store Key and Row bytes separately (WalChange's shape) and a frozen type must
// be able to decode both independently.
[Generator]
public sealed class FrozenSchemaGenerator : IIncrementalGenerator {
    private const string FrozenSchemaAttributeFullName = "RhinoDB.Core.Tables.FrozenSchemaAttribute";
    private const string PrimaryKeyAttributeFullName = "RhinoDB.Core.Tables.PrimaryKeyAttribute";

    static private readonly DiagnosticDescriptor MissingPrimaryKeyDiagnostic = new(
        "RHINO022",
        "Frozen schema row missing [PrimaryKey]",
        "Row type '{0}' is [FrozenSchema]-attributed but declares no [PrimaryKey] parameter - a frozen "
        + "snapshot needs to know its key field the same way a live [Table] row does, since archived WAL "
        + "entries store Key and Row bytes separately and a frozen type must decode both independently",
        "RhinoDB.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var results = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                FrozenSchemaAttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => ToFrozenSchemaModel(ctx)
            );

        context.RegisterSourceOutput(results, static (spc, result) => {
            foreach (var diagnostic in result.Diagnostics) spc.ReportDiagnostic(diagnostic);
            if (result.Model is not null) spc.AddSource($"{result.Model.SimpleName}.FrozenSchema.g.cs", Emit(result.Model));
        });
    }

    static private (FrozenSchemaModel? Model, ImmutableArray<Diagnostic> Diagnostics) ToFrozenSchemaModel(GeneratorAttributeSyntaxContext ctx) {
        var type = (INamedTypeSymbol)ctx.TargetSymbol;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        var primaryCtor = SchemaWalk.FindPrimaryConstructor(type);
        var primaryKeyParam = primaryCtor?.Parameters.FirstOrDefault(p =>
            p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == PrimaryKeyAttributeFullName)
        );
        if (primaryCtor is null || primaryKeyParam is null) {
            diagnostics.Add(Diagnostic.Create(MissingPrimaryKeyDiagnostic, ctx.TargetNode.GetLocation(), type.Name));
            return (null, diagnostics.ToImmutable());
        }

        diagnostics.AddRange(SchemaWalk.CheckOtherKindFieldAttributes(primaryCtor.Parameters, type.Name, ctx.TargetNode.GetLocation()));
        if (diagnostics.Count > 0) return (null, diagnostics.ToImmutable());

        var fields = SchemaWalk.ToRowFieldModels(primaryCtor.Parameters);
        var revision = (int)ctx.Attributes[0].ConstructorArguments[0].Value!;

        var model = new FrozenSchemaModel(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString(),
            revision,
            primaryKeyParam.Name,
            primaryKeyParam.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            fields
        );
        return (model, diagnostics.ToImmutable());
    }

    static private string Emit(FrozenSchemaModel model) {
        var sb = new StringBuilder();
        var row = model.FullName;
        var key = model.PrimaryKeyTypeFullName;
        var opsName = $"{model.SimpleName}FrozenSchemaOps";
        var pkField = model.Fields.First(f => f.FieldName == model.PrimaryKeyName);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using RhinoDB.Core;");
        sb.AppendLine();
        if (model.Namespace is not null) {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {opsName} {{");
        sb.AppendLine($"    public const int Revision = {model.Revision};");
        sb.AppendLine();

        sb.AppendLine($"    public static byte[] SerializeRow({row} row) {{");
        sb.AppendLine("        var bufferWriter = new PooledBufferWriter(256);");
        sb.AppendLine("        var writerState = MemoryPackWriterOptionalStatePool.Rent(null);");
        sb.AppendLine("        var writer = new MemoryPackWriter<PooledBufferWriter>(ref bufferWriter, writerState);");
        foreach (var f in model.Fields) SchemaWalk.EmitWriteField(sb, f, $"row.{f.FieldName}");
        sb.AppendLine("        writer.Flush();");
        sb.AppendLine("        var result = bufferWriter.WrittenSpan.ToArray();");
        sb.AppendLine("        bufferWriter.Dispose();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static {row} DeserializeRow(byte[] bytes) {{");
        sb.AppendLine("        var readerState = MemoryPackReaderOptionalStatePool.Rent(null);");
        sb.AppendLine("        var reader = new MemoryPackReader(bytes, readerState);");
        foreach (var f in model.Fields) SchemaWalk.EmitReadField(sb, f);
        sb.AppendLine("        reader.Dispose();");
        sb.Append($"        return new {row}(");
        sb.Append(string.Join(", ", model.Fields.Select(f => $"{TableGenerator.Camel(f.FieldName)}Value")));
        sb.AppendLine(");");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static byte[] SerializeKey({key} key) {{");
        sb.AppendLine("        var bufferWriter = new PooledBufferWriter(32);");
        sb.AppendLine("        var writerState = MemoryPackWriterOptionalStatePool.Rent(null);");
        sb.AppendLine("        var writer = new MemoryPackWriter<PooledBufferWriter>(ref bufferWriter, writerState);");
        SchemaWalk.EmitWriteField(sb, pkField, "key");
        sb.AppendLine("        writer.Flush();");
        sb.AppendLine("        var result = bufferWriter.WrittenSpan.ToArray();");
        sb.AppendLine("        bufferWriter.Dispose();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static {key} DeserializeKey(byte[] bytes) {{");
        sb.AppendLine("        var readerState = MemoryPackReaderOptionalStatePool.Rent(null);");
        sb.AppendLine("        var reader = new MemoryPackReader(bytes, readerState);");
        SchemaWalk.EmitReadField(sb, pkField);
        sb.AppendLine("        reader.Dispose();");
        sb.AppendLine($"        return {TableGenerator.Camel(pkField.FieldName)}Value;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class FrozenSchemaModel(
        string fullName, string simpleName, string? @namespace, int revision,
        string primaryKeyName, string primaryKeyTypeFullName, ImmutableArray<RowFieldModel> fields
    ) {
        public string FullName { get; } = fullName;
        public string SimpleName { get; } = simpleName;
        public string? Namespace { get; } = @namespace;
        public int Revision { get; } = revision;
        public string PrimaryKeyName { get; } = primaryKeyName;
        public string PrimaryKeyTypeFullName { get; } = primaryKeyTypeFullName;
        public ImmutableArray<RowFieldModel> Fields { get; } = fields;
    }
}
