using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RhinoDB.Generators;

[Generator]
public sealed class RhinoErrorGenerator : IIncrementalGenerator {
    private const string AttributeFullName = "RhinoDB.Core.Exceptions.GeneratesRhinoErrorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ToModel((INamedTypeSymbol)ctx.TargetSymbol))
            .Collect();

        context.RegisterSourceOutput(models, static (spc, errors) => Emit(spc, errors));
    }

    static private ErrorModel ToModel(INamedTypeSymbol exceptionType) {
        // Every exception here has exactly one constructor - the primary constructor
        // the exception declares itself with (e.g. `DuplicateKeyException(object key)`).
        var ctor = exceptionType.InstanceConstructors.First(c => c.Parameters.Length > 0);

        const string suffix = "Exception";
        var typeName = exceptionType.Name;
        var factoryName = typeName.EndsWith(suffix)
            ? typeName.Substring(0, typeName.Length - suffix.Length)
            : typeName;

        var parameters = ctor.Parameters
            .Select(p => new ParamModel(p.Name, p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .ToImmutableArray();

        return new ErrorModel(exceptionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), factoryName, parameters);
    }

    static private void Emit(SourceProductionContext context, ImmutableArray<ErrorModel> errors) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by RhinoDB.Generators.RhinoErrorGenerator from every [GeneratesRhinoError] exception.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RhinoDB.Core.Results;");
        sb.AppendLine();
        sb.AppendLine("public readonly partial struct RhinoError {");

        sb.AppendLine("    private enum Kind {");
        foreach (var error in errors) sb.AppendLine($"        {error.FactoryName},");
        sb.AppendLine("        Wrapped");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var error in errors) {
            var parameterList = string.Join(", ", error.Parameters.Select(p => $"{p.Type} {p.Name}"));
            var arguments = string.Join(", ", error.Parameters.Select(p => $"{SlotFor(p.Name)}: {p.Name}"));
            sb.AppendLine($"    static public RhinoError {error.FactoryName}({parameterList}) =>");
            sb.AppendLine($"        new(Kind.{error.FactoryName}, {arguments});");
            sb.AppendLine();
        }

        sb.AppendLine("    public Exception ToException() => kind switch {");
        foreach (var error in errors) {
            var arguments = string.Join(", ", error.Parameters.Select(p => AccessorFor(p.Name)));
            sb.AppendLine($"        Kind.{error.FactoryName} => new {error.ExceptionType}({arguments}),");
        }
        sb.AppendLine("        _ => wrapped ?? new Exception(\"Unexpected error, empty exception caught\")");
        sb.AppendLine("    };");

        sb.AppendLine("}");

        context.AddSource("RhinoError.g.cs", sb.ToString());
    }

    // The fixed storage slots RhinoError.cs declares by hand. A parameter name that
    // doesn't match one of these has nowhere to live, so it's a build error rather
    // than a silently wrong generated file.
    static private string SlotFor(string parameterName) => parameterName switch {
        "key" => "key",
        "attemptedKey" => "attemptedKey",
        "offset" => "offset",
        _ => throw new InvalidOperationException(
            $"RhinoErrorGenerator: no RhinoError slot for constructor parameter '{parameterName}'. " +
            "Add a matching field to RhinoError.cs and a case to RhinoErrorGenerator.SlotFor/AccessorFor.")
    };

    static private string AccessorFor(string parameterName) => parameterName switch {
        "key" => "key!",
        "attemptedKey" => "attemptedKey!",
        "offset" => "offset",
        _ => throw new InvalidOperationException(
            $"RhinoErrorGenerator: no RhinoError slot for constructor parameter '{parameterName}'.")
    };

    private sealed class ErrorModel(string exceptionType, string factoryName, ImmutableArray<ParamModel> parameters) {
        public string ExceptionType { get; } = exceptionType;
        public string FactoryName { get; } = factoryName;
        public ImmutableArray<ParamModel> Parameters { get; } = parameters;
    }

    private sealed class ParamModel(string name, string type) {
        public string Name { get; } = name;
        public string Type { get; } = type;
    }
}
