<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RhinoDB.Tools.Dev</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RhinoDB.PreBuild\RhinoDB.PreBuild.csproj" />
    </ItemGroup>

</Project>
