<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RhinoDB.Sandbox</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RhinoDB.Core\RhinoDB.Core.csproj" />
        <ProjectReference Include="..\RhinoDB.Lib\RhinoDB.Lib.csproj" />
        <ProjectReference Include="..\RhinoDB.Generators\RhinoDB.Generators.csproj"
                           OutputItemType="Analyzer"
                           ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\RhinoDB.SchemaContracts\RhinoDB.SchemaContracts.csproj"
                           OutputItemType="Analyzer"
                           ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\RhinoDB.PreBuild\RhinoDB.PreBuild.csproj"
                           ReferenceOutputAssembly="false" />
    </ItemGroup>

    <Import Project="..\RhinoDB.PreBuild\build\RhinoDB.PreBuild.props" />

    <Import Project="..\RhinoDB.PreBuild\build\RhinoDB.PreBuild.targets" />

</Project>
