using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using RhinoDB.SchemaContracts;

namespace RhinoDB.Generators;

[Generator]
public sealed class ChildDatabaseGenerator : IIncrementalGenerator {
    static private readonly DiagnosticDescriptor ChildDatabaseRootNotDeclaredDiagnostic = new(
        "RHINO037",
        "[ChildDatabase<TRoot,TKey>]'s TRoot is not a declared [Database]",
        "'{0}' is [ChildDatabase<{1}, ...>]-attributed, but '{1}' has no [Database] attribute anywhere in "
        + "this compilation - a child's TRoot must be a real, declared Root database type",
        "RhinoDB.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var declaredRootFullNames = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DatabaseDiscovery.DatabaseAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => DatabaseDiscovery.ToDatabaseModel(ctx))
            .Collect()
            .Select(static (dbs, _) => dbs.Select(d => d.FullName).ToImmutableArray());

        var children = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DatabaseDiscovery.ChildDatabaseAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ToChildModel(ctx))
            .Collect();

        var combined = children.Combine(declaredRootFullNames);

        context.RegisterSourceOutput(combined, static (spc, pair) => Emit(spc, pair.Left, pair.Right));
    }

    static private ChildModel ToChildModel(GeneratorAttributeSyntaxContext ctx) {
        var database = DatabaseDiscovery.ToDatabaseModel(ctx);
        var (rootFullName, keyFullName) = DatabaseDiscovery.ToChildDatabaseTypeArgs(ctx);
        return new ChildModel(database, rootFullName, keyFullName);
    }

    static private void Emit(SourceProductionContext context, ImmutableArray<ChildModel> children, ImmutableArray<string> declaredRootFullNames) {
        var valid = ImmutableArray.CreateBuilder<ChildModel>();
        foreach (var child in children) {
            if (!declaredRootFullNames.Contains(child.RootFullName)) {
                context.ReportDiagnostic(Diagnostic.Create(
                    ChildDatabaseRootNotDeclaredDiagnostic, Location.None, child.Database.SimpleName, child.RootFullName));
                continue;
            }
            valid.Add(child);
        }

        if (valid.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by RhinoDB.Generators.ChildDatabaseGenerator from every [ChildDatabase<TRoot,TKey>] type.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RhinoDB.Lib.Hosting;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedChildDatabases {");
        sb.AppendLine("    public static RhinoHostBuilder AddGeneratedChildDatabases(this RhinoHostBuilder builder) {");
        foreach (var child in valid) {
            var dbType = child.Database.FullName;
            var txType = child.Database.FullName + "Transaction";
            sb.AppendLine($"        builder.AddChildDatabase<{dbType}, {txType}, {child.KeyFullName}>(options => options.CreateDb = cold => new {dbType}(cold));");
        }
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedChildDatabases.g.cs", sb.ToString());
    }

    private sealed class ChildModel(DatabaseModel database, string rootFullName, string keyFullName) {
        public DatabaseModel Database { get; } = database;
        public string RootFullName { get; } = rootFullName;
        public string KeyFullName { get; } = keyFullName;
    }
}
