using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using RhinoDB.SchemaContracts;

namespace RhinoDB.Generators;

[Generator]
public sealed class CustomTypeGenerator : IIncrementalGenerator {
    static private readonly DiagnosticDescriptor MissingSerializationAttributesDiagnostic = new(
        "RHINO017",
        "CustomType missing mandatory IDC/client serialization attributes",
        "Type '{0}' is [CustomType]-attributed but is missing {1} - every custom type must carry both "
        + "[MemoryPackable] and [MessagePackObject], the same mandatory contract [Table] row types have, "
        + "so IDC and client access always have a real, source-generated formatter available",
        "RhinoDB.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var configProtocol = context.AdditionalTextsProvider
            .Where(static t => Path.GetFileName(t.Path) == "config.json")
            .Collect()
            .Select(static (texts, ct) => {
                if (texts.Length == 0) return ClientProtocolKind.Raw;
                var text = texts[0].GetText(ct)?.ToString();
                if (string.IsNullOrEmpty(text)) return ClientProtocolKind.Raw;
                try {
                    var parsedConfig = GeneratorConfigLoader.Parse(text!);
                    return ClientProtocolParser.Parse(parsedConfig.ClientProtocol);
                } catch {
                    return ClientProtocolKind.Raw;
                }
            });

        var results = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                SchemaWalk.CustomTypeAttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => ctx
            )
            .Combine(configProtocol)
            .Select(static (pair, _) => ToCustomTypeModel(pair.Left, pair.Right));

        context.RegisterSourceOutput(results, static (spc, result) => {
            foreach (var diagnostic in result.Diagnostics) spc.ReportDiagnostic(diagnostic);
            if (result.Model is not null) spc.AddSource($"{result.Model.SimpleName}.CustomType.g.cs", Emit(result.Model, result.ClientProtocol));
        });
    }

    static private (CustomTypeModel? Model, ImmutableArray<Diagnostic> Diagnostics, ClientProtocolKind ClientProtocol) ToCustomTypeModel(
        GeneratorAttributeSyntaxContext ctx, ClientProtocolKind clientProtocol) {
        var type = (INamedTypeSymbol)ctx.TargetSymbol;
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();

        var missingSerializationAttrs = ImmutableArray.CreateBuilder<string>();
        if (clientProtocol == ClientProtocolKind.VersionedMemoryPack && !SchemaWalk.HasMemoryPackable(type)) missingSerializationAttrs.Add("[MemoryPackable]");
        if (clientProtocol == ClientProtocolKind.MessagePack && !SchemaWalk.HasMessagePackObject(type)) missingSerializationAttrs.Add("[MessagePackObject]");
        if (missingSerializationAttrs.Count > 0) {
            diagnostics.Add(Diagnostic.Create(
                MissingSerializationAttributesDiagnostic, ctx.TargetNode.GetLocation(), type.Name, string.Join(" and ", missingSerializationAttrs)));
            return (null, diagnostics.ToImmutable(), clientProtocol);
        }

        var primaryCtor = type.InstanceConstructors.FirstOrDefault(c =>
            c.Parameters.Length > 0 && !(c.Parameters.Length == 1 && SymbolEqualityComparer.Default.Equals(c.Parameters[0].Type, type))
        );

        if (primaryCtor is not null) {
            diagnostics.AddRange(SchemaWalk.CheckOtherKindFieldAttributes(primaryCtor.Parameters, type.Name, ctx.TargetNode.GetLocation(), clientProtocol));
            if (diagnostics.Count > 0) return (null, diagnostics.ToImmutable(), clientProtocol);
        }

        var fields = primaryCtor is null
            ? ImmutableArray<RowFieldModel>.Empty
            : SchemaWalk.ToRowFieldModels(primaryCtor.Parameters);

        var model = new CustomTypeModel(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            type.Name,
            type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString(),
            fields
        );
        return (model, diagnostics.ToImmutable(), clientProtocol);
    }

    static private string Emit(CustomTypeModel model, ClientProtocolKind clientProtocol) {
        var sb = new StringBuilder();
        var type = model.FullName;
        var opsName = $"{model.SimpleName}CustomTypeOps";

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using MemoryPack;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using RhinoDB.Core;");
        sb.AppendLine();
        if (model.Namespace is not null) {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {opsName} {{");

        sb.AppendLine($"    internal static void WriteRaw<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, {type} value) where TBufferWriter : IBufferWriter<byte> {{");
        foreach (var f in model.Fields) SchemaWalk.EmitWriteField(sb, f, $"value.{f.FieldName}");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static {type} ReadRaw(ref MemoryPackReader reader) {{");
        foreach (var f in model.Fields) SchemaWalk.EmitReadField(sb, f);
        sb.Append($"        return new {type}(");
        sb.Append(string.Join(", ", model.Fields.Select(f => $"{TableGenerator.Camel(f.FieldName)}Value")));
        sb.AppendLine(");");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static byte[] SerializeRow({type} value) {{");
        sb.AppendLine("        var bufferWriter = new PooledBufferWriter(256);");
        sb.AppendLine("        var writerState = MemoryPackWriterOptionalStatePool.Rent(null);");
        sb.AppendLine("        var writer = new MemoryPackWriter<PooledBufferWriter>(ref bufferWriter, writerState);");
        sb.AppendLine("        WriteRaw(ref writer, value);");
        sb.AppendLine("        writer.Flush();");
        sb.AppendLine("        var result = bufferWriter.WrittenSpan.ToArray();");
        sb.AppendLine("        bufferWriter.Dispose();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    internal static {type} DeserializeRow(byte[] bytes) {{");
        sb.AppendLine("        var readerState = MemoryPackReaderOptionalStatePool.Rent(null);");
        sb.AppendLine("        var reader = new MemoryPackReader(bytes, readerState);");
        sb.AppendLine("        var result = ReadRaw(ref reader);");
        sb.AppendLine("        reader.Dispose();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        SchemaWalk.EmitProtocolWrapperMethods(sb, type, clientProtocol);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private sealed class CustomTypeModel(string fullName, string simpleName, string? @namespace, ImmutableArray<RowFieldModel> fields) {
        public string FullName { get; } = fullName;
        public string SimpleName { get; } = simpleName;
        public string? Namespace { get; } = @namespace;
        public ImmutableArray<RowFieldModel> Fields { get; } = fields;
    }
}
