using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RhinoDB.Generators;

[Generator]
public sealed class DbErrorGenerator : IIncrementalGenerator {
    private const string AttributeFullName = "RhinoDB.Core.Exceptions.GenerateDbErrorAttribute";
    private const string CoreAssemblyName = "RhinoDB.Core";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var exceptionModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ToExceptionModel((INamedTypeSymbol)ctx.TargetSymbol))
            .Collect();

        var enumModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (ctx, _) => ToEnumModel((INamedTypeSymbol)ctx.TargetSymbol));

        var coreOutput = context.CompilationProvider.Combine(exceptionModels);
        context.RegisterSourceOutput(coreOutput, static (spc, source) => {
            if (source.Left.AssemblyName == CoreAssemblyName) EmitCore(spc, source.Right);
        });

        context.RegisterSourceOutput(enumModels, static (spc, enumModel) => EmitEnumHelper(spc, enumModel));
    }

    static private ExceptionModel ToExceptionModel(INamedTypeSymbol exceptionType) {
        const string suffix = "Exception";
        var typeName = exceptionType.Name;
        var factoryName = typeName.EndsWith(suffix)
            ? typeName.Substring(0, typeName.Length - suffix.Length)
            : typeName;

        return new ExceptionModel(exceptionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), factoryName);
    }

    static private EnumModel ToEnumModel(INamedTypeSymbol enumType) {
        var companionName = enumType.Name == "Err" ? "Errors" : "Err";

        var members = enumType.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static f => f.IsConst)
            .Select(static f => f.Name)
            .ToImmutableArray();

        return new EnumModel(
            enumType.ContainingNamespace.IsGlobalNamespace ? null : enumType.ContainingNamespace.ToDisplayString(),
            enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            enumType.Name,
            companionName,
            members);
    }

    static private void EmitCore(SourceProductionContext context, ImmutableArray<ExceptionModel> errors) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by RhinoDB.Generators.DbErrorGenerator from every [GenerateDbError] exception.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RhinoDB.Core;");
        sb.AppendLine();

        sb.AppendLine("public enum ErrorKind : byte {");
        sb.AppendLine("    SystemFailure,");
        foreach (var error in errors)
            sb.AppendLine($"    {error.FactoryName},");
        sb.AppendLine("    Custom,");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public readonly partial struct DbError {");
        sb.AppendLine("    public ushort CustomCode { get; }");
        sb.AppendLine();
        foreach (var error in errors)
            sb.AppendLine($"    public static DbError {error.FactoryName}(Exception? inner = null) => new(ErrorKind.{error.FactoryName}, inner);");
        sb.AppendLine();

        sb.AppendLine("    private DbError(ushort customCode, Exception? inner = null) {");
        sb.AppendLine("        Kind = ErrorKind.Custom;");
        sb.AppendLine("        CustomCode = customCode;");
        sb.AppendLine("        systemException = inner;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static DbError Custom(ushort code, Exception? inner = null) => new(code, inner);");
        sb.AppendLine();

        sb.AppendLine("    public Exception ToException() => Kind switch {");
        sb.AppendLine("        ErrorKind.SystemFailure => systemException!,");
        sb.AppendLine("        ErrorKind.Custom => new Exception($\"Custom database error (code {CustomCode})\", systemException),");
        foreach (var error in errors)
            sb.AppendLine($"        ErrorKind.{error.FactoryName} => new {error.ExceptionType}(systemException),");
        sb.AppendLine("        _ => new Exception(\"Unexpected error, empty exception caught\")");
        sb.AppendLine("    };");

        sb.AppendLine("}");

        context.AddSource("DbError.g.cs", sb.ToString());
    }

    static private void EmitEnumHelper(SourceProductionContext context, EnumModel enumModel) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by RhinoDB.Generators.DbErrorGenerator for [GenerateDbError] enum {enumModel.EnumName}.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using RhinoDB.Core;");
        sb.AppendLine();
        if (enumModel.Namespace is not null) {
            sb.AppendLine($"namespace {enumModel.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public static class {enumModel.CompanionName} {{");
        foreach (var member in enumModel.Members)
            sb.AppendLine($"    public static DbError {member}() => DbError.Custom((ushort){enumModel.FullyQualifiedEnumType}.{member});");
        sb.AppendLine();
        sb.AppendLine($"    public static bool Is(this DbError error, {enumModel.FullyQualifiedEnumType} kind) =>");
        sb.AppendLine("        error.Kind == ErrorKind.Custom && error.CustomCode == (ushort)kind;");
        sb.AppendLine("}");

        context.AddSource($"{(enumModel.Namespace ?? "global")}.{enumModel.EnumName}.g.cs", sb.ToString());
    }

    private sealed class ExceptionModel(string exceptionType, string factoryName) {
        public string ExceptionType { get; } = exceptionType;
        public string FactoryName { get; } = factoryName;
    }

    private sealed class EnumModel(string? @namespace, string fullyQualifiedEnumType, string enumName, string companionName, ImmutableArray<string> members) {
        public string? Namespace { get; } = @namespace;
        public string FullyQualifiedEnumType { get; } = fullyQualifiedEnumType;
        public string EnumName { get; } = enumName;
        public string CompanionName { get; } = companionName;
        public ImmutableArray<string> Members { get; } = members;
    }
}
