using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using RhinoDB.SchemaContracts;

namespace RhinoDB.Generators;

[Generator]
public sealed class TransactionSugarGenerator : IIncrementalGenerator {
    private const string MultiTransactionMetadataName = "RhinoDB.Lib.Execution.PlannedMultiTx";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var roots = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                DatabaseDiscovery.DatabaseAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => {
                    var model = DatabaseDiscovery.ToDatabaseModel(ctx);
                    return (FullName: model.FullName, SimpleName: model.SimpleName);
                })
            .Collect();

        var children = DatabaseDiscovery
            .ChildDatabases(context, static (ctx, _) => {
                var (rootFullName, keyFullName) = DatabaseDiscovery.ToChildDatabaseTypeArgs(ctx);
                var model = DatabaseDiscovery.ToDatabaseModel(ctx);
                return (FullName: model.FullName, SimpleName: model.SimpleName, RootFullName: rootFullName, KeyFullName: keyFullName);
            })
            .Collect();

        var libReferenced = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(MultiTransactionMetadataName) is not null);

        context.RegisterSourceOutput(roots.Combine(children).Combine(libReferenced), static (spc, pair) => {
            if (!pair.Right) return;
            var source = Emit(pair.Left.Left, pair.Left.Right);
            if (source is not null) spc.AddSource("GeneratedTransactionSugar.g.cs", source);
        });
    }

    static private string? Emit(
        ImmutableArray<(string FullName, string SimpleName)> roots,
        ImmutableArray<(string FullName, string SimpleName, string RootFullName, string? KeyFullName)> children) {
        // A child whose TRoot isn't declared already gets RHINO037 from ChildDatabaseGenerator - just skip it here.
        var validChildren = children.Where(c => roots.Any(r => r.FullName == c.RootFullName)).ToImmutableArray();
        if (roots.Length == 0 && validChildren.Length == 0) return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by RhinoDB.Generators.TransactionSugarGenerator from every [Database], [ChildDatabase<TRoot,TKey>] and [ChildDatabase<TRoot>] type.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace RhinoDB.Lib.Execution;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedTransactionSugar {");

        const string ctx = "global::RhinoDB.Lib.Execution.RhinoCtx";
        const string multi = "global::RhinoDB.Lib.Execution.PlannedMultiTx";
        const string result = "global::RhinoDB.Core.Result";
        const string task = "global::System.Threading.Tasks.Task";
        const string func = "global::System.Func";
        const string value = "global::RhinoDB.Lib.Execution.TxValue";
        const string locked = "global::RhinoDB.Lib.Execution.LockedMultiTx";
        const string declare = "global::RhinoDB.Lib.Execution.MultiTxParticipants";

        foreach (var (db, simpleName) in roots) {
            var tx = db + "Transaction";
            sb.AppendLine($"    // ---- {db} (Root) ----");
            sb.AppendLine($"    public static {task}<{result}> BeginTx(this {ctx} ctx, {func}<{db}, {tx}, {result}> body) => ctx.BeginTx<{db}, {tx}>(body);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> BeginTx<TValue>(this {ctx} ctx, {func}<{db}, {tx}, {result}<TValue>> body) => ctx.BeginTx<{db}, {tx}, TValue>(body);");
            sb.AppendLine($"    public static {multi} Add(this {multi} multiTx, {func}<{db}, {tx}, {result}> body) => multiTx.Add<{db}, {tx}>(body);");
            sb.AppendLine($"    public static {multi} Add<TArgs>(this {multi} multiTx, {func}<{db}, {tx}, TArgs, {result}> body, TArgs args) => multiTx.Add<{db}, {tx}, TArgs>(body, args);");
            sb.AppendLine($"    public static {value}<TValue> Add<TValue>(this {multi} multiTx, {func}<{db}, {tx}, {result}<TValue>> body) => multiTx.Add<{db}, {tx}, TValue>(body);");
            sb.AppendLine($"    public static {value}<TValue> Add<TArgs, TValue>(this {multi} multiTx, {func}<{db}, {tx}, TArgs, {result}<TValue>> body, TArgs args) => multiTx.Add<{db}, {tx}, TArgs, TValue>(body, args);");
            sb.AppendLine($"    public static {declare} {simpleName}(this {declare} participants) => participants.Root<{db}, {tx}>();");
            sb.AppendLine($"    public static {task}<{result}> Run(this {locked} open, {func}<{db}, {tx}, {result}> body) => open.Run<{db}, {tx}>(body);");
            sb.AppendLine($"    public static {task}<{result}> Run<TArgs>(this {locked} open, {func}<{db}, {tx}, TArgs, {result}> body, TArgs args) => open.Run<{db}, {tx}, TArgs>(body, args);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> Run<TValue>(this {locked} open, {func}<{db}, {tx}, {result}<TValue>> body) => open.Run<{db}, {tx}, TValue>(body);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> Run<TArgs, TValue>(this {locked} open, {func}<{db}, {tx}, TArgs, {result}<TValue>> body, TArgs args) => open.Run<{db}, {tx}, TArgs, TValue>(body, args);");
            sb.AppendLine();
        }

        // Singletons: keyless, like the Root - the fixed internal key is passed for the caller.
        const string singletonKey = "global::RhinoDB.Lib.Hosting.SingletonChild.Key";
        foreach (var (db, simpleName, rootFullName, _) in validChildren.Where(c => c.KeyFullName is null)) {
            var tx = db + "Transaction";
            const string key = "string";
            sb.AppendLine($"    // ---- {db} (singleton Child of {rootFullName}) ----");
            sb.AppendLine($"    public static {task}<{result}> BeginTx(this {ctx} ctx, {func}<{db}, {tx}, {result}> body) => ctx.BeginTx<{db}, {tx}, {key}>({singletonKey}, body);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> BeginTx<TValue>(this {ctx} ctx, {func}<{db}, {tx}, {result}<TValue>> body) => ctx.BeginTx<{db}, {tx}, {key}, TValue>({singletonKey}, body);");
            sb.AppendLine($"    public static {multi} Add(this {multi} multiTx, {func}<{db}, {tx}, {result}> body) => multiTx.Add<{db}, {tx}, {key}>({singletonKey}, body);");
            sb.AppendLine($"    public static {multi} Add<TArgs>(this {multi} multiTx, {func}<{db}, {tx}, TArgs, {result}> body, TArgs args) => multiTx.Add<{db}, {tx}, {key}, TArgs>({singletonKey}, body, args);");
            sb.AppendLine($"    public static {value}<TValue> Add<TValue>(this {multi} multiTx, {func}<{db}, {tx}, {result}<TValue>> body) => multiTx.Add<{db}, {tx}, {key}, TValue>({singletonKey}, body);");
            sb.AppendLine($"    public static {value}<TValue> Add<TArgs, TValue>(this {multi} multiTx, {func}<{db}, {tx}, TArgs, {result}<TValue>> body, TArgs args) => multiTx.Add<{db}, {tx}, {key}, TArgs, TValue>({singletonKey}, body, args);");
            sb.AppendLine($"    public static {declare} {simpleName}(this {declare} participants) => participants.Child<{db}, {tx}, {key}>({singletonKey});");
            sb.AppendLine($"    public static {task}<{result}> Run(this {locked} open, {func}<{db}, {tx}, {result}> body) => open.Run<{db}, {tx}, {key}>({singletonKey}, body);");
            sb.AppendLine($"    public static {task}<{result}> Run<TArgs>(this {locked} open, {func}<{db}, {tx}, TArgs, {result}> body, TArgs args) => open.Run<{db}, {tx}, {key}, TArgs>({singletonKey}, body, args);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> Run<TValue>(this {locked} open, {func}<{db}, {tx}, {result}<TValue>> body) => open.Run<{db}, {tx}, {key}, TValue>({singletonKey}, body);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> Run<TArgs, TValue>(this {locked} open, {func}<{db}, {tx}, TArgs, {result}<TValue>> body, TArgs args) => open.Run<{db}, {tx}, {key}, TArgs, TValue>({singletonKey}, body, args);");
            sb.AppendLine();
        }

        foreach (var child in validChildren.Where(c => c.KeyFullName is not null)) {
            var db = child.FullName;
            var simpleName = child.SimpleName;
            var tx = db + "Transaction";
            var key = child.KeyFullName!;
            sb.AppendLine($"    // ---- {db} (Child of {child.RootFullName}, keyed by {key}) ----");
            sb.AppendLine($"    public static {task}<{result}> BeginTx(this {ctx} ctx, {key} key, {func}<{db}, {tx}, {result}> body) => ctx.BeginTx<{db}, {tx}, {key}>(key, body);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> BeginTx<TValue>(this {ctx} ctx, {key} key, {func}<{db}, {tx}, {result}<TValue>> body) => ctx.BeginTx<{db}, {tx}, {key}, TValue>(key, body);");
            sb.AppendLine($"    public static {multi} Add(this {multi} multiTx, {key} key, {func}<{db}, {tx}, {result}> body) => multiTx.Add<{db}, {tx}, {key}>(key, body);");
            sb.AppendLine($"    public static {multi} Add<TArgs>(this {multi} multiTx, {key} key, {func}<{db}, {tx}, TArgs, {result}> body, TArgs args) => multiTx.Add<{db}, {tx}, {key}, TArgs>(key, body, args);");
            sb.AppendLine($"    public static {value}<TValue> Add<TValue>(this {multi} multiTx, {key} key, {func}<{db}, {tx}, {result}<TValue>> body) => multiTx.Add<{db}, {tx}, {key}, TValue>(key, body);");
            sb.AppendLine($"    public static {value}<TValue> Add<TArgs, TValue>(this {multi} multiTx, {key} key, {func}<{db}, {tx}, TArgs, {result}<TValue>> body, TArgs args) => multiTx.Add<{db}, {tx}, {key}, TArgs, TValue>(key, body, args);");
            sb.AppendLine($"    public static {declare} {simpleName}(this {declare} participants, {key} key) => participants.Child<{db}, {tx}, {key}>(key);");
            sb.AppendLine($"    public static {task}<{result}> Run(this {locked} open, {key} key, {func}<{db}, {tx}, {result}> body) => open.Run<{db}, {tx}, {key}>(key, body);");
            sb.AppendLine($"    public static {task}<{result}> Run<TArgs>(this {locked} open, {key} key, {func}<{db}, {tx}, TArgs, {result}> body, TArgs args) => open.Run<{db}, {tx}, {key}, TArgs>(key, body, args);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> Run<TValue>(this {locked} open, {key} key, {func}<{db}, {tx}, {result}<TValue>> body) => open.Run<{db}, {tx}, {key}, TValue>(key, body);");
            sb.AppendLine($"    public static {task}<{result}<TValue>> Run<TArgs, TValue>(this {locked} open, {key} key, {func}<{db}, {tx}, TArgs, {result}<TValue>> body, TArgs args) => open.Run<{db}, {tx}, {key}, TArgs, TValue>(key, body, args);");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
